export const NEW_THOUGHT_INIT = 'NEW_THOUGHT_INIT';
export const NEW_THOUGHT_SUCCESS = 'NEW_THOUGHT_SUCCESS';
export const NEW_THOUGHT_FAILED = 'NEW_THOUGHT_FAILED';

export const EDIT_THOUGHT_INIT = 'EDIT_THOUGHT_INIT';
export const EDIT_THOUGHT_SUCCESS = 'EDIT_THOUGHT_SUCCESS';
export const EDIT_THOUGHT_FAILED = 'EDIT_THOUGHT_FAILED';

export const FETCH_THOUGHT_INIT = 'FETCH_THOUGHT_INIT';
export const FETCH_THOUGHT_SUCCESS = 'FETCH_THOUGHT_SUCCESS';
export const FETCH_THOUGHT_FAILED = 'FETCH_THOUGHT_FAILED';

export const THOUGHT_LIST_FETCH_INIT = 'THOUGHT_LIST_FETCH_INIT';
export const THOUGHT_LIST_FETCH_SUCCESS = 'THOUGHT_LIST_FETCH_SUCCESS';
export const THOUGHT_LIST_FETCH_FAILED = 'THOUGHT_LIST_FETCH_FAILED';

export const DELETE_THOUGHT_INIT = 'DELETE_THOUGHT_INIT';
export const DELETE_THOUGHT_CONFIRM = 'DELETE_THOUGHT_CONFIRM';
export const DELETE_THOUGHT_SUCCESS = 'DELETE_THOUGHT_SUCCESS';
export const DELETE_THOUGHT_FAILED = 'DELETE_THOUGHT_FAILED';
export const DELETE_THOUGHT_CANCEL = 'DELETE_THOUGHT_CANCEL';